### ISSUE TITLE
Request: Machine ID should overwrite global.toml

### ISSUE THREAD

**Issue by tmhoule** [groob/moroz#17]
My expected behavior is that a workstation uses global.toml and then applies differences from a specific machine.toml file.  A nice enhancement would be to have the global.toml file with all base settings, then 'override' just certain entries with a machine.toml file.

**Comment by groob** [comment]
That's already how it works. From the README:

> Moroz expects a global.toml file which contains a list of rules. The global config can be overriden by providing a machine specific config. To do so, name the file for each host with the santa machine id configuration parameter. By default, this is the hardware UUID of the mac.

Is this not working for you? 

Note that there is no nesting. `machine_id.toml` replaces `global.toml` entirely.

**Comment by tmhoule** [comment]
My mistake.  I had a folder 'backup' with old configs in there.  Apparently, Moroz read through that stuff so I was getting unexpected errors.  Thank you!
