### ISSUE TITLE
Fighting with other Resources on the server

### ISSUE THREAD

**Issue by kcgaisford** [groob/moroz#20]
I set up my Moroz instance on a server that I already had. (Its a Foreman/Puppet Server) I didn't think it would really have any problems because moroz seems to be 'Santa' TCP listener. 

But Moroz seems to be competing with Foreman for resources on the server, and it slowly escalates until the server is maxed out. 

My current load is ` load average: 0.13, 0.32, 1.00`, but when I woke up this morning the server was rocking 44.00 across the board. Had to kill a few services and restart them. 

I know this is an environment issue, but is there any way to cap the resources that Moroz is trying to use?

**Comment by groob** [comment]
You can cap resources with systemd. Consult the systemd documentation for how to do that. 

I'm wondering about the load issue, is there a resource leak maybe? All moroz is really doing is reading files from disk and serving them over HTTP, and that is not so expensive. Do you have a large fleet? How often does Santa check in?
